project_folder: "MyTaifexDataProject"
database_name: "processed_data.duckdb"
log_name: "pipeline.log"
local_workspace: "/tmp/taifex_data_workspace"
remote_base_path: "/content/drive/MyDrive"
directories:
  input: "00_input"
  processed: "01_processed"
  archive: "02_archive"
  quarantine: "03_quarantine"
  db: "98_database"
  log: "99_logs"
